# Generated by Django 5.1 on 2024-08-26 12:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offerletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferLetter',
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
