# Generated by Django 5.1 on 2024-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_offerletter_usertemplate_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemplate',
            name='title',
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='content',
            field=models.TextField(),
        ),
    ]
