# Generated by Django 5.1 on 2024-08-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usertemplate_title_alter_usertemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
