# Generated by Django 5.1 on 2024-08-27 06:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usertemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
