# Generated by Django 5.1 on 2024-08-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usertemplate_title_alter_usertemplate_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemplate',
            name='title',
        ),
    ]
