# Generated by Django 5.1 on 2024-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_usertemplate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
